### ISSUE TITLE
flyme9可以用了

### ISSUE THREAD

**Issue by axieshi** [FSpaceCore/SpaceCore#1]
flyme9终于没有无限弹窗了，谢谢开发者。。
但发现很多小问题，比较明显的一个：测试了京东app长按选择"清除数据"后将无法再次打开，造成系统卡顿。。另外测试via浏览器时倒是可以打开。
多肝几个版本出来，加油！哈哈
(魅族18s android11+flyme9.3.0.0A)

**Comment by axieshi** [comment]
试了，重启app之后能打开。
还有那个访问外部app的功能，分身via浏览器后可以调起qq，但是授权登录的时候无法跳转回来。。然后测试京东登录时直接就显示未安装微信、qq

**Comment by FSpaceCore** [comment]
正常，那个功能只是为了能感知外部app是否存在，登录什么的，还是需要再内部登录。

Sent with [Proton Mail](https://proton.me/) secure email.

------- Original Message -------
