### ISSUE TITLE
snapchat app not working

### ISSUE THREAD

**Issue by twuijri** [FSpaceCore/SpaceCore#10]
Snapchat app does not work and sends an error that there are no Google services

![Screenshot_2022-09-21-00-10-59-457-edit_com.fdemo64.jpg](https://user-images.githubusercontent.com/11951128/191365308-7de673b7-9df9-47da-93ab-909d23c7e992.jpg)

Also, I can't switch to English, the app stays on Chinese

**Comment by FSpaceCore** [comment]
Demo does not support gms

**Comment by twuijri** [comment]
Is there a paid version?

**Comment by FSpaceCore** [comment]
look readme
