### ISSUE TITLE
English language?

### ISSUE THREAD

**Issue by NSTAdventure** [FSpaceCore/SpaceCore#11]
Ig title say everything.
Do this project will have english language in the future?

**Comment by FSpaceCore** [comment]
It is expected to be released today or tomorrow

**Comment by NSTAdventure** [comment]
> It is expected to be released today or tomorrow

Yes sir
Anyway mind to enable discussion tab? I want to ask something 🤔

**Comment by FSpaceCore** [comment]
enabled
