### ISSUE TITLE
[bug]

### ISSUE THREAD

**Issue by axieshi** [FSpaceCore/SpaceCore#14]
1，设备伪装-重置设备信息，这里多点两次会闪屏闪退一下
2，美团京东依旧无法调用微信登录，调用时会直接闪退或者回到桌面。

**Comment by FSpaceCore** [comment]
美团测试没问题，多等一下。

**Comment by axieshi** [comment]
汗。那就比较尴尬了，我测试了不行。还重新卸载安装过。可能咱系统不同，我魅族18s android11 flyme9 。

**Comment by axieshi** [comment]
美团验证码登录方式，发发验证码时显示请求异常，发不出去。

**Comment by FSpaceCore** [comment]
> 美团验证码登录方式，发发验证码时显示请求异常，发不出去。

这种风控力很强的应用就不用看了。

**Comment by zlz3371062** [comment]
我 applictioan 调用 init 就 直接 com.fvbox.lib.FCore.getService(:33)  这 啥毛病。。。。

**Comment by FSpaceCore** [comment]
> 我 applictioan 调用 init 就 直接 com.fvbox.lib.FCore.getService(:33) 这 啥毛病。。。。

系统多少
