### ISSUE TITLE
能不能加个钉钉和企业微信的虚拟单位

### ISSUE THREAD

**Issue by ewfubwefwe** [FSpaceCore/SpaceCore#17]
能不能加个钉钉和企业微信的虚拟定位打卡

**Comment by sudami** [comment]
> 能不能加个钉钉和企业微信的虚拟定位打卡

企业微信的虚拟定位打卡，可以用比翼多开
https://sudami.lanzoul.com/bydknew
https://www.123pan.com/s/fVlKVv-tJ3Fv
