### ISSUE TITLE
bug

### ISSUE THREAD

**Issue by axieshi** [FSpaceCore/SpaceCore#20]
魅族18s flyme9 android11
1、京东金融app在使用京东app进行登录时会调用外部的京东，而不是调用内部京东的分身。（访问外部App的功能并未开启）
2、点击还原数据访问本机文件管理器时卡死！

**Comment by FSpaceCore** [comment]
第一个问题，试下3.1，我这边测试没问题。
第二个问题，最好能提供日志。
