### ISSUE TITLE
大多数app都无法分身，只有个别的几个可以，无法使用

### ISSUE THREAD

**Issue by jack20209527** [FSpaceCore/SpaceCore#30]

**Comment by jack20209527** [comment]
最新版本和旧版都试过了，都不行

**Comment by jack20209527** [comment]
其实FCore的测试自己全面的测测就知道了，如果but太多改不过来，我可以协助改改，让大伙早点用起来，哎。
看了之前的帖子，总让提供日志，这玩意机型多、app类型也多，就得靠自己做全面兼容测试并修复才能彻底，否则发现一个改一个，几年也改不完。

**Comment by FSpaceCore** [comment]
这种东西要不就是加固，要么就是检测，这类居多。

**Comment by jack20209527** [comment]
然后呢，有什么建议吗？那个问题怎么解决？或者我们怎么规避呢，比如spacecore sdk提供一个apk，给不能分身的app挑出来我们做个标记，不让用户调用分身是不是能好点，比崩溃强啊
