### ISSUE TITLE
有个重大问题啊

### ISSUE THREAD

**Issue by ggiidd** [FSpaceCore/SpaceCore#36]
安卓清理君可以读取外部文件，你这个沙盒不行啊，希望尽快修复吧。毕竟还有一些人用这个是为了隐私

![Screenshot_2023_0607_162603.png](https://github.com/FSpaceCore/SpaceCore/assets/116434731/a282906b-53d4-4745-992f-d9ce06a09997)

**Comment by FSpaceCore** [comment]
这一块默认规则是共享的

**Comment by ggiidd** [comment]
> 这一块默认规则是共享的

那能不能提供一个开关让应用无法访问。另外能有更多权限比如剪贴板之类的就更好了

**Comment by FSpaceCore** [comment]
这块我后面完善一下。
