### ISSUE TITLE
你好，我这有个需求请帮忙评估一下？

### ISSUE THREAD

**Issue by xmtggh** [FSpaceCore/SpaceCore#38]
我需要做一个类似华为投屏功能里面的那个桌面模式的开发，相当于在安卓的虚拟屏上面开发一个独立的launcher，然后把这个屏幕投屏到另一个显示器上面，请问一下你们这个框架能实现吗？需求是要求能在虚拟屏里面打开其他的activity

**Comment by FSpaceCore** [comment]
是可以的啊，好像没有什么特别的
