### ISSUE TITLE
bug&&建议

### ISSUE THREAD

**Issue by axieshi** [FSpaceCore/SpaceCore#4]
试用了下挺不错的，怎么没人用呢？？

1，开始用的美团play版，启动会卡黑屏，然后升级了下国内版最新的美团就可以正常打开。
2，饿了么、建设生活定位有问题。（总体上定位似乎bug较多）
3，美团在调用微信登录时也卡闪退
4，建议
:)能否在释放内存时同步清理后台卡片
:)空间名称的更改希望同步在任务卡片中
:)增加设备伪装的数据可备份功能

**Comment by FSpaceCore** [comment]
释放内存时清理后台卡片功能有，未开放。其他问题待优化
