### ISSUE TITLE
oppo手机无法启动分身使用的V2

### ISSUE THREAD

**Issue by devlookme** [FSpaceCore/SpaceCore#43]
System.err: java.lang.RuntimeException: Unable to create application com.cssq.walke.App: java.lang.RuntimeException: android.os.DeadSystemException
06-21 11:11:00.642 12995 12995 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7270)
06-21 11:11:00.642 12995 12995 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 11:11:00.642 12995 12995 W System.err: 	at top.niunaijun.blackreflection.utils.Reflector.callByCaller(:3)
06-21 11:11:00.642 12995 12995 W System.err: 	at top.niunaijun.blackreflection.BlackReflection$1.invoke(:86)
06-21 11:11:00.642 12995 12995 W System.err: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
06-21 11:11:00.642 12995 12995 W System.err: 	at $Proxy148.handleBindApplication(Unknown Source)
06-21 11:11:00.642 12995 12995 W System.err: 	at w0.c(:873)
06-21 11:11:00.642 12995 12995 W System.err: 	at w0.c(:1248)
06-21 11:11:00.642 12995 12995 W System.err: 	at a1.a(:57)
06-21 11:11:00.642 12995 12995 W System.err: 	at a1.handleMessage(:5)
06-21 11:11:00.642 12995 12995 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 11:11:00.642 12995 12995 W System.err: 	at android.os.Looper.loop(Looper.java:263)
06-21 11:11:00.642 12995 12995 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8292)
06-21 11:11:00.642 12995 12995 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 11:11:00.642 12995 12995 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
06-21 11:11:00.642 12995 12995 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
06-21 11:11:00.642 12995 13080 W libc    : Unable to set property "debug.binderinfo.capture" to "true": connection failed; errno=13 (Permission denied)
06-21 11:11:00.643 12995 12995 W System.err: Caused by: java.lang.RuntimeException: android.os.DeadSystemException
06-21 11:11:00.643 12995 12995 W System.err: 	at android.net.ConnectivityManager.getAllNetworkInfo(ConnectivityManager.java:1269)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.AriaConfig.isNetworkAvailable(AriaConfig.java:17)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.AriaConfig.regNetCallBack(AriaConfig.java:1)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.AriaConfig.initData(AriaConfig.java:6)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.AriaConfig.init(AriaConfig.java:21)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.AriaManager.initData(AriaManager.java:3)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.AriaManager.init(AriaManager.java:21)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.Aria.get(Aria.java:3)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.arialyy.aria.core.Aria.init(Aria.java:1)
06-21 11:11:00.643 12995 12995 W System.err: 	at dnjh.qH3TDEwU(AriaDownloadManagement.kt:6)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.cssq.walke.config.B8ZH.oGrP0S(AppConfig.kt:271)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.cssq.walke.config.B8ZH.RO3Zm9G(AppConfig.kt:73)
06-21 11:11:00.643 12995 12995 W System.err: 	at com.cssq.walke.App.onCreate(App.kt:31)
06-21 11:11:00.643 12995 12995 W System.err: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1193)
06-21 11:11:00.643 12995 12995 W System.err: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:7265)
06-21 11:11:00.643 12995 12995 W System.err: 	... 15 more
06-21 11:11:00.643 12995 12995 W System.err: Caused by: android.os.DeadSystemException
06-21 11:11:00.643 12995 12995 W System.err: 	... 30 more
06-21 11:11:00.644 12995 12995 D BoxApplication: afterCreatedApplication: application=com.cssq.walke.App@f633c38, packageName=com.happy.walker, processName=com.happy.walker, userId=1
06-21 11:11:00.649 12995 13062 W libc    : Unable to set property "debug.binderinfo.capture" to "true": connection failed; errno=13 (Permission denied)
06-21 11:11:00.650 12995 13080 W libc    : Unable to set property "debug.binderinfo.capture" to "true": connection failed; errno=13 (Permission denied)
06-21 11:11:00.651 23940 23999 W bkpv    : Empty content. Thus might mean that the settings are not synced down.
06-21 11:11:00.652 12995 12995 W System.err: android.os.DeadObjectException
06-21 11:11:00.652 12995 13062 E Parcel  : Reading a NULL string not supported here.
06-21 11:11:00.652 12995 12995 W System.err: 	at android.os.BinderProxy.transactNative(Native Method)
06-21 11:11:00.652 12995 12995 W System.err: 	at android.os.BinderProxy.transact(BinderProxy.java:568)
06-21 11:11:00.653 12995 12995 W System.err: 	at android.app.IActivityManager$Stub$Proxy.getTaskForActivity(IActivityManager.java:5866)
06-21 11:11:00.653 12995 12995 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 11:11:00.653 12995 12995 W System.err: 	at top.niunaijun.blackreflection.utils.Reflector.callByCaller(:3)
06-21 11:11:00.653 12995 12995 W System.err: 	at top.niunaijun.blackreflection.BlackReflection$1.invoke(:86)
06-21 11:11:00.653 12995 12995 W System.err: 	at java.lang.reflect.Proxy.invoke(Proxy.java:1006)
06-21 11:11:00.653 12995 12995 W System.err: 	at $Proxy174.getTaskForActivity(Unknown Source)
06-21 11:11:00.653 12995 12995 W System.err: 	at a1.a(:965)
06-21 11:11:00.653 12995 12995 W System.err: 	at a1.handleMessage(:5)
06-21 11:11:00.653 12995 12995 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 11:11:00.653 12995 12995 W System.err: 	at android.os.Looper.loop(Looper.java:263)
06-21 11:11:00.653 12995 12995 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8292)
06-21 11:11:00.653 12995 12995 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 11:11:00.653 12995 12995 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
06-21 11:11:00.653 12995 12995 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
06-21 11:11:00.653 12995 12995 E Parcel  : Reading a NULL string not supported here.
06-21 11:11:00.655 12995 12995 W libc    : Unable to set property "debug.binderinfo.capture" to "true": connection failed; errno=13 (Permission denied)
06-21 11:11:00.655 12995 12995 W System.err: java.lang.RuntimeException: android.os.DeadSystemException
06-21 11:11:00.655 12995 12995 W System.err: 	at android.app.ActivityThread.acquireProvider(ActivityThread.java:7401)
06-21 11:11:00.655 12995 12995 W System.err: 	at android.app.ContextImpl$ApplicationContentResolver.acquireProvider(ContextImpl.java:3019)
06-21 11:11:00.655 12995 12995 W System.err: 	at android.content.ContentResolver.acquireProvider(ContentResolver.java:2497)
06-21 11:11:00.655 12995 12995 W System.err: 	at android.content.ContentResolver.call(ContentResolver.java:2432)
06-21 11:11:00.655 12995 12995 W System.err: 	at android.content.ContentResolver.call(ContentResolver.java:2417)
06-21 11:11:00.656 12995 12995 W System.err: 	at com.fvbox.lib.system.FSystemProvider$a.a(:2)
06-21 11:11:00.656 12995 12995 W System.err: 	at com.fvbox.lib.FCore.getService(:31)
06-21 11:11:00.656 12995 12995 W System.err: 	at l4$a.a(:9)
06-21 11:11:00.656 12995 12995 W System.err: 	at a1.a(:972)
06-21 11:11:00.656 12995 12995 W System.err: 	at a1.handleMessage(:5)
06-21 11:11:00.656 12995 12995 W System.err: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 11:11:00.656 12995 12995 W System.err: 	at android.os.Looper.loop(Looper.java:263)
06-21 11:11:00.656 12995 12995 W System.err: 	at android.app.ActivityThread.main(ActivityThread.java:8292)
06-21 11:11:00.656 12995 12995 W System.err: 	at java.lang.reflect.Method.invoke(Native Method)
06-21 11:11:00.656 12995 12995 W System.err: 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:612)
06-21 11:11:00.656 12995 12995 W System.err: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1006)
06-21 11:11:00.656 12995 13062 W Settings: Can't get key multi_sim_data_call from content://settings/global
06-21 11:11:00.656 12995 13062 W Settings: android.os.DeadObjectException
06-21 11:11:00.656 12995 13062 W Settings: 	at android.os.BinderProxy.transactNative(Native Method)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.os.BinderProxy.transact(BinderProxy.java:568)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:471)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2869)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.provider.Settings$Global.getStringForUser(Settings.java:13563)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.provider.Settings$Global.getString(Settings.java:13551)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.provider.Settings$Global.getInt(Settings.java:13756)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getSubId(TelephonyManager.java:6919)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getPhoneId(TelephonyManager.java:6954)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getSimCountryIso(TelephonyManager.java:3828)
06-21 11:11:00.656 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.q.a(Unknown Source:29)
06-21 11:11:00.656 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.k2.e(Unknown Source:288)
06-21 11:11:00.656 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.v1.handleMessage(Unknown Source:195)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.os.Looper.loop(Looper.java:263)
06-21 11:11:00.656 12995 13062 W Settings: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-21 11:11:00.656 12995 12995 W System.err: Caused by: android.os.DeadSystemException
06-21 11:11:00.656 12995 12995 W System.err: 	... 16 more
06-21 11:11:00.659 12995 13062 E Parcel  : Reading a NULL string not supported here.
06-21 11:11:00.659  1527  5445 D DisplayManagerService: Display listener for pid 10640 died.
06-21 11:11:00.661 23940 23968 W OplusExSystemServiceHelper: checkOplusExSystemService intent getComponent is null
06-21 11:11:00.661  1527  5458 W ActivityManager: Scheduling restart of crashed service com.google.android.gms/.chimera.GmsIntentOperationService in 1000ms for start-requested
06-21 11:11:00.665  1527  1737 D PowerManagerService: setScreenBrightnessOverrideFromWindowManagerInternal brightness=NaN mScreenBrightnessOverrideFromWindowManager=NaN
06-21 11:11:00.665 17065 17091 E RemoteGuardClient.DWB.ActivityMonitor: onProcessDied com.google.uid.shared:10031 pid = 10640 uid = 10031
06-21 11:11:00.667 12995 13062 W Settings: Can't get key multi_sim_data_call from content://settings/global
06-21 11:11:00.667 12995 13062 W Settings: android.os.DeadObjectException
06-21 11:11:00.667 12995 13062 W Settings: 	at android.os.BinderProxy.transactNative(Native Method)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.os.BinderProxy.transact(BinderProxy.java:568)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:471)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2869)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.provider.Settings$Global.getStringForUser(Settings.java:13563)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.provider.Settings$Global.getString(Settings.java:13551)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.provider.Settings$Global.getInt(Settings.java:13756)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getSubId(TelephonyManager.java:6919)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getNetworkOperatorName(TelephonyManager.java:2710)
06-21 11:11:00.667 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.r.a(Unknown Source:30)
06-21 11:11:00.667 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.k2.e(Unknown Source:288)
06-21 11:11:00.667 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.v1.handleMessage(Unknown Source:195)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.os.Looper.loop(Looper.java:263)
06-21 11:11:00.667 12995 13062 W Settings: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-21 11:11:00.668   740   740 I Zygote  : Process 10640 exited due to signal 9 (Killed)
06-21 11:11:00.671 12995 13062 E Parcel  : Reading a NULL string not supported here.
06-21 11:11:00.672 12995 12995 W libc    : Unable to set property "debug.binderinfo.capture" to "true": connection failed; errno=13 (Permission denied)
06-21 11:11:00.672 12995 12995 D AndroidRuntime: Shutting down VM
06-21 11:11:00.672 12995 13062 W Settings: Can't get key multi_sim_data_call from content://settings/global
06-21 11:11:00.672 12995 13062 W Settings: android.os.DeadObjectException
06-21 11:11:00.672 12995 13062 W Settings: 	at android.os.BinderProxy.transactNative(Native Method)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.os.BinderProxy.transact(BinderProxy.java:568)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.content.ContentProviderProxy.query(ContentProviderNative.java:471)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.provider.Settings$NameValueCache.getStringForUser(Settings.java:2869)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.provider.Settings$Global.getStringForUser(Settings.java:13563)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.provider.Settings$Global.getString(Settings.java:13551)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.provider.Settings$Global.getInt(Settings.java:13756)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getSubId(TelephonyManager.java:6919)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getPhoneId(TelephonyManager.java:6954)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.telephony.TelephonyManager.getNetworkOperator(TelephonyManager.java:2737)
06-21 11:11:00.672 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.r.a(Unknown Source:39)
06-21 11:11:00.672 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.k2.e(Unknown Source:288)
06-21 11:11:00.672 12995 13062 W Settings: 	at bykvm_19do.bykvm_19do.bykvm_19do.v1.handleMessage(Unknown Source:195)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.os.Handler.dispatchMessage(Handler.java:102)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.os.Looper.loop(Looper.java:263)
06-21 11:11:00.672 12995 13062 W Settings: 	at android.os.HandlerThread.run(HandlerThread.java:67)
06-21 11:11:00.673 12995 12995 E AndroidRuntime: FATAL EXCEPTION: main
06-21 11:11:00.673 12995 12995 E AndroidRuntime: Process: com.happy.walker, PID: 12995

**Comment by FSpaceCore** [comment]
所有应用都是吗

**Comment by devlookme** [comment]
> 所有应用都是吗

基本上是所有的应用，(自己写的测试demo可以进入)，市面上的app基本没有启动成功

**Comment by devlookme** [comment]
并且点击启动后手机就特别卡了，

**Comment by devlookme** [comment]
试了另外一个oppo手机也是同样问题

**Comment by FSpaceCore** [comment]
已修复：https://github.com/FSpaceCore/SpaceCore/releases/tag/v3
