### ISSUE TITLE
支持模拟位置吗，有没有设置定位坐标的示例代码，文档上写的有方法，但是没有具体参数的说明

### ISSUE THREAD

**Issue by xiaomaxuetu** [FSpaceCore/SpaceCore#52]
我在 DeviceMapping.kt这个文件里加了如下代码
`private var mLocaton: FLocation? = FCore.get().getLocation(userID,"test")

var location: String = ""
        get() {
            return "${mLocaton?.longitude},${mLocaton?.latitude}"
        }
        set(value) {
            field = value
            var lng = value.split(",").first().toDouble()
            var lat = value.split(",").last().toDouble()
            FCore.get().setLocationEnable(userID,"test",enable)
            FCore.get().setLocation(userID,"test",FLocation(lat,lng))
        }
`
设置和获取是生效的，但是高德之类的软件还是真实的位置信息

**Comment by FSpaceCore** [comment]
高德有基站定位，目前内核只支持gps，不生效很正常。
