### ISSUE TITLE
1.2安装不上

### ISSUE THREAD

**Issue by axieshi** [FSpaceCore/SpaceCore#6]
如题，本机原来安装有1.0  现在安装不上1.2。

**Comment by nnjun** [comment]
> 如题，本机原来安装有1.0  现在安装不上1.2。

卸载掉可以吧？

**Comment by FSpaceCore** [comment]
卸载掉旧版的话可以安装吗？

**Comment by axieshi** [comment]
有空等我本机备份后再试试吧&nbsp; &nbsp; vmos虚拟机那个软件里边我都安装不上，这个上面没安装过旧版。
&nbsp;


啊些事丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 上午10:17
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FSpaceCore/SpaceCore] 1.2安装不上 (Issue #6)





 
卸载掉旧版的话可以安装吗？

**Comment by axieshi** [comment]
试了，本机卸载后照样无法安装

**Comment by FSpaceCore** [comment]
> 试了，本机卸载后照样无法安装

你用adb install看看有什么错误

**Comment by FSpaceCore** [comment]
我重新上传了两个包，应该可以了。

**Comment by axieshi** [comment]
测试了&nbsp; &nbsp;可以，并且覆盖安装也正常！！！对了，发现这个版本点击跳转app后，在多任务窗口看到主app的界面是跳转后app的开屏页，这点再修修？？



&nbsp;


啊些事丶
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年9月15日(星期四) 下午5:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [FSpaceCore/SpaceCore] 1.2安装不上 (Issue #6)





 
我重新上传了两个包，应该可以了。

**Comment by FSpaceCore** [comment]
这个也不算是bug，回去之后是消失的。有必要时再说吧

**Comment by FSpaceCore** [comment]
你可以试下现在最新的版本，如果不行的话确实要先卸载了。有导出数据功能，你可以先导出，到时候再还原数据。
