### ISSUE TITLE
引入aar文件后会导致AndroidStudio卡顿

### ISSUE THREAD

**Issue by AwakenDragon** [FSpaceCore/SpaceCore#61]
这是一个悲剧的问题，引入aar文件后会导致AndroidStudio巨卡无比，尤其是在智能提示方面，每输入一次至少要反应1分钟。移除引用后就会变得流畅无比。。。。
电脑配置
- 2023年14寸MacBookPro
- Apple M2 Max
- 64GB内存
- 1TB存储

Android Studio 
- 2022.3.1 Patch1
- Gradle Version 8.0
- Gradle Plugin Version 8.1.1
- Android Studio默认JDK17

studio.vmoptions
-Xms2048m
-Xmx2048m
-XX:ReservedCodeCacheSize=2048m

**Comment by ugreek85** [comment]
I have the same problem

**Comment by zhinuotech** [comment]
me too!!! cpu 7950x  memory 64G ddr5 6400, nvme

**Comment by FSpaceCore** [comment]
暂时不清楚为什么，没出现这个问题

**Comment by AwakenDragon** [comment]
不知清楚原因就这么把issue给关了？难道以后也不想解决了？

**Comment by yinshuai0324** [comment]
cao，我还以为是我AS的问题，卸载、降级。搞了好几遍。发现还是没解决。看到这个issue 切换到其他项目 巨流畅。

**Comment by jing1007209484** [comment]
我也是一样的问题  估计有猫腻

**Comment by Faisal-FS** [comment]
I have the same problem but couldn't find any solution for this. However, if I comment out the aar file implementation in gradle file then this does not occur. After that I have to comment out the code which uses this sdk and work on the rest of the app.
