### ISSUE TITLE
Google拼音输入法在双开的app中无法运行

### ISSUE THREAD

**Issue by hunhun010164** [FSpaceCore/SpaceCore#63]
手机恢复过出厂,然后安装了google拼音输入法,在其他的app中都能正常切换(无论是全键盘还是9宫格),但是双开出来的微信中,虽然也可以选中google拼音键盘,但是实际无效,仍旧只能输入英文的全键盘.
又拿了一台手机恢复出厂测试,一样的情况.
之后拿中国移动的app测试了一下,也是一样的问题,google输入法用不了
不过讯飞,搜狗都没有问题.
望能查一下,谢谢

**Comment by hunhun010164** [comment]
另外,想问一下,如果之后有更新,是如何安装?应该不能先卸载旧版吧?这样的话,双开的微信也被卸载了,聊天记录也没了.
如果是直接安装,不会影响双开的微信的聊天记录吧?谢谢

**Comment by FSpaceCore** [comment]
不会影响外部的微信哦

**Comment by FSpaceCore** [comment]
输入法是已知问题，需要加个设置才可以。
