### ISSUE TITLE
无法安装？

### ISSUE THREAD

**Issue by FMYC2015** [FSpaceCore/SpaceCore#8]
这个属于什么BUG？系统鸿蒙OS2.0

**Comment by FMYC2015** [comment]
两部手机一部可以安装，一部安装失败

**Comment by FSpaceCore** [comment]
鸿蒙测试可以按照，是否下载最新的release？

**Comment by axieshi** [comment]
> 鸿蒙测试可以按照，是否下载最新的release？

老哥，修复美团微信登录的包传一传呗。 （话说你有群吗？tg啥的也行，提bug方便些，嘿嘿。。）

**Comment by FSpaceCore** [comment]
> > 鸿蒙测试可以按照，是否下载最新的release？
> 
> 老哥，修复美团微信登录的包传一传呗。 （话说你有群吗？tg啥的也行，提bug方便些，嘿嘿。。）

主页不是有tg吗

**Comment by FMYC2015** [comment]
> 鸿蒙测试可以按照，是否下载最新的release？

最新版本的包

**Comment by FSpaceCore** [comment]
> > 鸿蒙测试可以按照，是否下载最新的release？
> 
> 最新版本的包

那我暂时没条件测试出来，中间是更新过一个版本的。要是你重新下载安装也是不行，那就帮不到你了。等下个版本看看吧
